### ISSUE TITLE
Why not finetune DPR using the results of GAR?

### ISSUE THREAD

**Issue by bunny-sleepy** [morningmoni/GAR#12]
It seems like dense retrieval may achieve better results, but in GAR+ you only fuse the results of sparse and dense retrieval, so why not finetune DPR using the augmented querys? Or if you have carried out such experiements, what is the performance?

**Comment by morningmoni** [comment]
Indeed. It's possible that finetuning DPR using augmented queries performs even better, but we didn't conduct such experiments since it's a bit costly and using BM25 already performs well. I am interested in knowing the results if you try it!
