### ISSUE TITLE
What is the difference between the two checkpoints？

### ISSUE THREAD

**Issue by XY2323819551** [morningmoni/GAR#13]
I noticed that there were two checkpoints when I finished training model，are they the same? 
I have trained three checkpoints based on custom datasets，but I got the same checkpoints'name, they are: ①checkpointepoch=1.ckpt；and②checkpointlast.ckpt 

So why is it *epoch=1, and not 50 or 100?("--num_train_epochs", default=8)

**Comment by morningmoni** [comment]
I think it stores the best and last ckpt. If epoch=1 then you may check if the first epoch is already the best one?

**Comment by XY2323819551** [comment]
> 
I thought the same thing before, but thought it was incredible to reach the best in the first epoch ......
