### ISSUE TITLE
Example of calling the RIDER function from DPR inference code

### ISSUE THREAD

**Issue by kambehmw** [morningmoni/GAR#14]
Thank you for sharing your implementation of GAR and RIDER.
there is a function called rider_rerank, I would appreciate if you could advise me how you actually used this in your DPR reader inference code. If possible, could you give an example of how you called it?

**Comment by morningmoni** [comment]
Can you take a look at the docstring?  Basically, you need to load the retriever data (`data`) and prepare a reader prediction dict (`q2pred`). The function will save a reranked list to `data` with key=`key`. You can then use the `write_rerank_psg` function to write the top ranked docs in `data` for reader inference. It's not "the DPR reader" btw, but a generative reader that takes top-10  docs.


def rider_rerank(data, q2pred, n_ctxs=100, n_pred=5, key='ctxs_rerank_100psg', mode='normal'):
    """
    @param data: the retriever results in the same format of DPR
    @param q2pred: a dict with key=question and value=[a list of predicted answers of some reader]
    @param n_ctxs: num of passages to use
    @param n_pred: num of reader predictions to use
    @param key: the key under which reranked passages are stored
    @param mode: 'normal' is the method described in the paper,
    'interleave' tries to cover different answers by interleaving the matched psg,
    'density' consider #answers matched in each psg

**Comment by kambehmw** [comment]
Yes, I have read the docstring. However, it didn't look like you were using the `rider_rerank` function in `dpr/train_reader.py`, which is why I asked. If I were to use DPR's `train_reader.py` to do the inference, would the following steps be correct?

- Using the docs before being reranked as input, do the inference with `train_reader.py`, and save the prediction results.
- Rerank the docs using the saved predictions and the `rider_rerank` function, and save the reranked docs results using the `write_rerank_psg` method.
- Run `train_reader.py` again with the reranked docs as input and perform inference.

**Comment by morningmoni** [comment]
Yes, it sounds about right. You may want to rerank 1000 and do inference on 100 to see if there is any improvement, or rerank on 100 and do inference on 10 to see if you can achieve comparable performance with faster inference.

**Comment by kambehmw** [comment]
Thank you for your answer that the flow of the above steps is roughly correct. I asked this question because I did not have an idea of how to implement it to apply RIDER to the inference of the DPR reader. I will try to actually implement it and see if it improves the score. Thanks.
