### ISSUE TITLE
Fusion quesion

### ISSUE THREAD

**Issue by zhengmq2010** [morningmoni/GAR#16]
Hi, I got a problem when I try to fusion the results from three sources following the instruction in another Issue "Say you have 3 lists of retrieved docs [a1, a2, ...], [b1, b2, ...], [c1, c2, ...]. The combined list would be [a1, b1, c1, a2, b2, c2, ...]". Especially, I treat list a, list b and list c as list answer, list sentence and list title separately. I check my code many time and I still obtain the result below slightly different, is it reasonable?
Top5 accuracy: 0.5853
Top10 accuracy: 0.6604
Top20 accuracy: 0.7269  
Top50 accuracy: 0.7967
Top100 accuracy: 0.8382

I use the provided augmented query using BM25 on NQ, and I got same results as another Issue in each source. 
Here is my fusion code, I would be grateful if you can point some mistake out. Or can you provide the resouce code? It would be really helpful!

`
def fusion(n_doc, tit=True, sen=True, ans_path=None, tit_path=None, sen_path=None, output_path=None):
    if tit:
        data_tit = json.load(open(tit_path, "r"))
    if sen:
        data_sen = json.load(open(sen_path, "r"))
    data_ans = json.load(open(ans_path, "r"))

    fusion_result = []
    for i, data in enumerate(data_ans):
        fusion_result.append(data)  # I do this to keep same format with the evaluation file
        fusion_psgs = []
        for j, ctx in enumerate(data["ctxs"]):
            fusion_psgs.append(ctx)
            if len(fusion_psgs) == n_doc:
                break
            if tit:
                fusion_psgs.append(data_tit[i]["ctxs"][j])
            if sen:
                fusion_psgs.append(data_sen[i]["ctxs"][j])
        assert len(fusion_psgs) == n_doc, f"question{i} fusion passages length{len(fusion_psgs)} != {n_doc}"
        fusion_result[i]["ctxs"] = fusion_psgs

    json.dump(fusion_result, open(output_path, "w"))
    return fusion_result
`

Thank you !!!

**Comment by morningmoni** [comment]
>  I got same results as another Issue in each source 

If you have comparable performance in each source already, can you try deduplication? The same passage could be retrieved from multiple sources.

**Comment by zhengmq2010** [comment]
Thanks! This solves my problem. Here is my fusion result.
Top1	accuracy: 0.3568
Top5	accuracy: 0.6075
Top10	accuracy: 0.6806
Top20	accuracy: 0.7468
Top50	accuracy: 0.8130
Top100	accuracy: 0.8463
I have another question. Does GAR+DPR has the same fusion way with GAR? If it does, which retrieved list is placed ahead?

**Comment by morningmoni** [comment]
yes, you can basically treat DPR's list as another source and place it the first of the four.

**Comment by zhengmq2010** [comment]
Thanks!! Here is my fusion result.
Top1	accuracy: 0.4693
Top5	accuracy: 0.7036
Top10	accuracy: 0.7615
Top20	accuracy: 0.8116
Top50	accuracy: 0.8645
Top100	accuracy: 0.8884
