### ISSUE TITLE
Model checkpoints

### ISSUE THREAD

**Issue by JulesGM** [morningmoni/GAR#2]
Hello!
Thanks for publishing your code. Do you intend to publish the checkpoint? The command-line arguments that you used to generate them would also be very nice.
Thanks.

**Comment by JulesGM** [comment]
(Or the eventual correspondence with those in the `train_gen.yml` file)

**Comment by morningmoni** [comment]
Hi,
We probably won't publish the checkpoints. It should be relatively easy to reproduce as we mostly use the default hyperparameters for seq2seq (I won't be surprised if you get better performance by tuning more carefully :). Besides `train_gen.yml`, You can refer to [conf.py](https://github.com/morningmoni/GAR/blob/master/gar/conf.py#L48) for the specific arguments.
