### ISSUE TITLE
Is the DPR code different from the Repo?

### ISSUE THREAD

**Issue by JulesGM** [morningmoni/GAR#4]
You include the DPR github code without making it a git submodule. Have you changed it from the repo or is it the same, aside from the `train_reader.py` file?

**Comment by morningmoni** [comment]
[reader_data.py](https://github.com/morningmoni/GAR/blob/master/dpr/data/reader_data.py#L97) is slightly improved to make specifying arguments more easily. Prediction results are saved in [train_reader.py](https://github.com/morningmoni/GAR/blob/master/dpr/train_reader.py#L523) for the passage-level span voting described in the paper.
The reader model itself and other files should be the same.
