### ISSUE TITLE
Question about training Answer_generator (GAR)

### ISSUE THREAD

**Issue by yiyaxiaozhi** [morningmoni/GAR#6]
How are the data look like for training an answer_generator and where are they?
I do not find any information about the variable  "data_dir="./cnn-dailymail/cnn_dm/ " of class SummarizationDataset in file utils_gen.py line 156.
How should I download and prepare the training data for answer_generator?

**Comment by morningmoni** [comment]
Please see https://github.com/morningmoni/GAR#data. We now publish the data for GAR training to make it easier. If you want to do it yourself, first download the original dataset and then prepare two files: the input is the question and the output is the answer.

**Comment by yiyaxiaozhi** [comment]
Thanks a lot！
It helps to understand the training process of GAR clearly.
