### ISSUE TITLE
Question about GAR and the Rider

### ISSUE THREAD

**Issue by yiyaxiaozhi** [morningmoni/GAR#7]
Thanks for your wonderful work. It brings a new angle to the IR task.
I am confused about the GAR generator and the prediction answer produced by a generator reader for Rider to reranks.
In my view, the format of input data for GAR is :
[start_token] question [end_token]
and the target is:
[start_token] answer/sentence/title [end_token] 
while the format for the reader is :
[start_token] question [separate_token] passage [end_token]
What is the relationship between the GAR generator and the generator which provides the prediction for reranking?
Are these two independent models?  
In addition, the call to the file rider.py was not found in the exposed code. Could you provide some instruction on it?

**Comment by morningmoni** [comment]
GAR is only used for retrieval, while Rider uses the reader's predictions.
> Are these two independent models? 

Yes, they are.

> In addition, the call to the file rider.py was not found in the exposed code. Could you provide some instruction on it?

Can you take a look at the in-line comments of rider.py?
