### ISSUE TITLE
GAR Data Files Missing

### ISSUE THREAD

**Issue by ronakice** [morningmoni/GAR#8]
I was going through the provided GAR data files for NQ. It seems like `nq-title` is missing all `test.target` files. It will be great if this can be updated to include it.

**Comment by morningmoni** [comment]
It is indeed missing and may not be found very easily... I can take another look later. But on the other hand, we didn't regularly check the test performance anyway. Once you train the model using train/val, you may use test.source.full as the input and generate all the titles on the test set.
