### ISSUE TITLE
NaNs and default fp16

### ISSUE THREAD

**Issue by JulesGM** [morningmoni/GAR#9]
Hello,
Just to say that fp16 defaults to on. On my config at least, I get NaNs when it's turned on. 
Also, the argument has `default=True` and `action="store_true"` by the way, which is a bit weird and makes me think it's supposed to be `default=False`.

```
parser.add_argument(
        "--fp16",
        action='store_true',
        default=True,
        help="Whether to use 16-bit (mixed) precision (through NVIDIA apex) instead of 32-bit",
    )
```
https://github.com/morningmoni/GAR/blob/master/gar/conf.py#L102

**Comment by morningmoni** [comment]
Thanks for the feedback. We did use fp16 to save training time without issues tho. I had similar experiences (NaNs) on another project but didn't figure out why fp16 wouldn't work sometimes. I now set the default to False.
